import type { AiThreatAssessment, LogEventType, LogSeverity } from '@aegis-core/contracts';

import type { AiAnalysisLogInput, AiAnalysisProvider } from './ai-analysis-provider.js';

type ThreatScenario = {
  threatLabel: string;
  recommendedAction: string;
  reasoningFragments: string[];
  baseConfidence: number;
};

const severityWeight: Record<LogSeverity, number> = {
  info: 8,
  low: 16,
  medium: 28,
  high: 38,
  critical: 48,
};

const defaultScenarioByEventType: Record<LogEventType, ThreatScenario> = {
  authentication: {
    threatLabel: 'Credential Access Attempt',
    recommendedAction:
      'Review authentication history, verify the source identity, and enforce MFA or password reset if the behavior is unexpected.',
    reasoningFragments: ['the event originated from authentication telemetry'],
    baseConfidence: 44,
  },
  process_execution: {
    threatLabel: 'Suspicious Process Execution',
    recommendedAction:
      'Inspect the parent process chain, isolate the host if execution is unauthorized, and capture endpoint telemetry for containment.',
    reasoningFragments: ['the event was classified as process execution activity'],
    baseConfidence: 52,
  },
  network_traffic: {
    threatLabel: 'Suspicious Network Behavior',
    recommendedAction:
      'Validate the destination reputation, review outbound connections, and block the flow if it matches known malicious infrastructure.',
    reasoningFragments: ['the event reflects unusual network telemetry'],
    baseConfidence: 48,
  },
  email_security: {
    threatLabel: 'Potential Phishing Activity',
    recommendedAction:
      'Quarantine the email, identify affected recipients, and review attachment or link detonation results before user re-delivery.',
    reasoningFragments: ['the event was generated by email security controls'],
    baseConfidence: 50,
  },
  privilege_change: {
    threatLabel: 'Privilege Escalation Attempt',
    recommendedAction:
      'Validate the change request, revert unauthorized permission grants, and investigate the initiating identity for compromise.',
    reasoningFragments: ['the log records a privilege or entitlement change'],
    baseConfidence: 60,
  },
  file_activity: {
    threatLabel: 'Sensitive File Access Anomaly',
    recommendedAction:
      'Inspect the file path, confirm user intent, and review egress controls if the activity suggests staging or exfiltration.',
    reasoningFragments: ['the telemetry indicates notable file activity'],
    baseConfidence: 46,
  },
  cloud_audit: {
    threatLabel: 'Cloud Control Plane Anomaly',
    recommendedAction:
      'Review the affected cloud account, revoke suspicious credentials, and audit recent policy changes before broader remediation.',
    reasoningFragments: ['the event originated from cloud audit logging'],
    baseConfidence: 54,
  },
};

const keywordScenarios: Array<{
  keywords: string[];
  scenario: ThreatScenario;
  confidenceBoost: number;
}> = [
  {
    keywords: ['failed login', 'brute force', 'password spray', 'multiple login failures'],
    scenario: {
      threatLabel: 'Credential Brute Force',
      recommendedAction:
        'Block the originating source if confirmed malicious, review affected accounts, and tighten authentication controls.',
      reasoningFragments: ['multiple authentication-failure indicators were present in the event content'],
      baseConfidence: 60,
    },
    confidenceBoost: 16,
  },
  {
    keywords: ['powershell', 'encodedcommand', 'rundll32', 'wmic', 'mshta'],
    scenario: {
      threatLabel: 'Malicious Script Execution',
      recommendedAction:
        'Contain the endpoint, collect process lineage and command-line evidence, and block the execution chain if unauthorized.',
      reasoningFragments: ['script-execution tradecraft indicators were identified in the message or payload'],
      baseConfidence: 68,
    },
    confidenceBoost: 18,
  },
  {
    keywords: ['beacon', 'command-and-control', 'c2', 'tor exit', 'unusual dns', 'periodic callback'],
    scenario: {
      threatLabel: 'Command and Control Beaconing',
      recommendedAction:
        'Block outbound traffic to the destination, isolate the asset, and capture network telemetry for deeper threat hunting.',
      reasoningFragments: ['beaconing or command-and-control patterns were detected in network telemetry'],
      baseConfidence: 70,
    },
    confidenceBoost: 18,
  },
  {
    keywords: ['phish', 'spoofed sender', 'malicious attachment', 'credential harvest'],
    scenario: {
      threatLabel: 'Phishing Delivery Attempt',
      recommendedAction:
        'Quarantine the message, notify impacted users, and review mailbox and identity activity for follow-on compromise.',
      reasoningFragments: ['email-borne attack indicators were identified in the event content'],
      baseConfidence: 64,
    },
    confidenceBoost: 14,
  },
  {
    keywords: ['admin role', 'policy update', 'elevated permissions', 'sudo', 'role assignment'],
    scenario: {
      threatLabel: 'Privilege Escalation Activity',
      recommendedAction:
        'Review the change window, revoke unauthorized access, and validate the initiating identity and session context.',
      reasoningFragments: ['privilege escalation indicators were found in the message or raw payload'],
      baseConfidence: 72,
    },
    confidenceBoost: 12,
  },
  {
    keywords: ['exfiltration', 'archive created', 'bulk download', 'sensitive file', 'mass copy'],
    scenario: {
      threatLabel: 'Potential Data Exfiltration',
      recommendedAction:
        'Review user intent, inspect DLP or proxy telemetry, and isolate the host if data staging is confirmed.',
      reasoningFragments: ['file staging or data exfiltration signals were observed in the event context'],
      baseConfidence: 66,
    },
    confidenceBoost: 16,
  },
];

function clampConfidenceScore(value: number) {
  return Math.max(12, Math.min(99, Math.round(value)));
}

function stringifyRawData(rawData: AiAnalysisLogInput['rawData']) {
  if (!rawData) {
    return '';
  }

  try {
    return JSON.stringify(rawData).toLowerCase();
  } catch {
    return '';
  }
}

function deriveThreatScenario(log: AiAnalysisLogInput): ThreatScenario {
  const haystack = `${log.message} ${stringifyRawData(log.rawData)}`.toLowerCase();
  const matchingScenario = keywordScenarios.find(({ keywords }) =>
    keywords.some((keyword) => haystack.includes(keyword)),
  );

  return matchingScenario?.scenario ?? defaultScenarioByEventType[log.eventType];
}

function calculateConfidenceScore(log: AiAnalysisLogInput) {
  const haystack = `${log.message} ${stringifyRawData(log.rawData)}`.toLowerCase();
  const keywordMatch = keywordScenarios.find(({ keywords }) =>
    keywords.some((keyword) => haystack.includes(keyword)),
  );

  const statusWeight = log.status === 'investigating' ? 10 : log.status === 'reviewed' ? -4 : 0;
  const sourceWeight = /edr|siem|xdr|ids|cloud/i.test(log.source) ? 6 : 0;

  return clampConfidenceScore(
    (keywordMatch?.scenario.baseConfidence ?? defaultScenarioByEventType[log.eventType].baseConfidence) +
      severityWeight[log.severity] +
      (keywordMatch?.confidenceBoost ?? 0) +
      statusWeight +
      sourceWeight,
  );
}

function buildReasoningSummary(log: AiAnalysisLogInput, scenario: ThreatScenario, confidenceScore: number) {
  const details = [
    ...scenario.reasoningFragments,
    `the log severity was ${log.severity}`,
    `the event was recorded on host ${log.host}`,
  ];

  return `Mock analysis flagged ${scenario.threatLabel.toLowerCase()} because ${details.join(
    ', ',
  )}. The resulting confidence score is ${confidenceScore} based on event context and heuristic keyword matching.`;
}

function buildAssessment(log: AiAnalysisLogInput): AiThreatAssessment {
  const scenario = deriveThreatScenario(log);
  const confidenceScore = calculateConfidenceScore(log);

  return {
    threatLabel: scenario.threatLabel,
    confidenceScore,
    recommendedAction: scenario.recommendedAction,
    reasoningSummary: buildReasoningSummary(log, scenario, confidenceScore),
  };
}

export class MockAiAnalysisProvider implements AiAnalysisProvider {
  readonly name = 'mock' as const;

  analyzeLog(log: AiAnalysisLogInput) {
    return Promise.resolve(buildAssessment(log));
  }

  async analyzeBatch(logs: AiAnalysisLogInput[]) {
    return Promise.all(logs.map((log) => this.analyzeLog(log)));
  }
}
